### ISSUE TITLE
recording voice in the future

### ISSUE THREAD

**Issue by mouncg** [Rapptz/discord-ext-native-voice#1]
I would find it extremely helpful to be able to record voice channels inside my bot (not for malicious intentions) but for a voice recorder feature, would this be possible?

**Comment by scrazzz** [comment]
Yes, it is possible. MEE6 has this feature.

https://mee6.xyz/premium?s=header
scroll a bit down and you’ll see.

**Comment by Rapptz** [comment]
This isn't the place. This is an experimental repository for native voice sending, not receiving.
